target-version = "py313"
line-length = 88
fix = true

[lint]
select = [
    "F", "E", "W", "I", "UP", "C4", "FA", "ISC", "ICN",
    "RET", "SIM", "TID", "TC", "PTH", "TD", "NPY", "B",
    "ASYNC", "PERF", "FURB", "RUF", "ARG", "PIE",
]

ignore = [
    "E501",
    "B008",
    "B905",
]

fixable = ["ALL"]
unfixable = [
    "ISC001",
    "TD002",
]

[lint.isort]
known-first-party = ["app"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"